# Generated by Django 6.1.1 on 2026-09-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe de Suporte')),
                ('descricao', models.TextField(blank=True, verbose_name='Atribuições da Equipe')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail da Equipe')),
                ('ativa', models.BooleanField(default=True, verbose_name='Equipe Ativa')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20, unique=True, verbose_name='Nível')),
                ('nome', models.CharField(max_length=50, verbose_name='Descrição da Prioridade')),
                ('peso', models.PositiveIntegerField(default=1, verbose_name='Peso de Ordenação')),
                ('cor_badge', models.CharField(default='info', max_length=20, verbose_name='Classe de Cor')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['peso'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='helpdesk.equipe', verbose_name='Equipe Responsável')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=30, unique=True, verbose_name='Protocolo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Assunto do Chamado')),
                ('descricao', models.TextField(verbose_name='Detalhamento do Problema')),
                ('solicitante_nome', models.CharField(max_length=120, verbose_name='Nome do Solicitante')),
                ('solicitante_email', models.EmailField(max_length=254, verbose_name='E-mail do Solicitante')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('prazo_sla', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Limite do SLA')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('solucao', models.TextField(blank=True, verbose_name='Parecer Técnico / Solução')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='helpdesk.categoria', verbose_name='Categoria')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='helpdesk.prioridade', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_resolucao', models.PositiveIntegerField(verbose_name='Tempo Máximo de SLA (Horas)')),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='Termo do Acordo')),
                ('prioridade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='helpdesk.prioridade', verbose_name='Prioridade Associada')),
            ],
            options={
                'verbose_name': 'Acordo de SLA',
                'verbose_name_plural': 'Acordos de SLA',
            },
        ),
    ]
